### ISSUE TITLE
Why Box2D.Common.Math.b2Vec2() is private?

### ISSUE THREAD

**Issue by Vlad-UA** [illandril/box2dweb-closure#5]
Hi Joe,

I have small question.
Why Box2D.Common.Math.b2Vec2() is private?  It used in many cases.
For example in the baseInit.js 
var world = new Box2D.Dynamics.b2World(new Box2D.Common.Math.b2Vec2(0, 9.8) /\* gravity _/, true /_ allowSleep */);

Thanks,
Vlad

PS  Thank you for the box2dweb-closure library.

**Comment by firecow** [comment]
Hi Vlad.

I don't think you are looking in the right project.

Constructor is private.
```new box2d.common.math.Vec2(x, y)```

Factory method is public.
```box2d.common.math.Vec2.get(x, y)```

This is the correct way to construct Vec2's, so the release/fetch mechanism is intact.

I can't even find baseInit.js you are referring to.

Yours
  Mads Jon

**Comment by illandril** [comment]
All uses of the constructor, outside of Box2D.Common.Math.b2Vec2.Get, are incorrect, and they should instead use Box2D.Common.Math.b2Vec2.Get.
The reason there are still incorrect uses in some of the test code is because I haven't had enough time (thanks to lots of other projects I've been busy with) and motivation (thanks to wonderful tools like Construct 2 and Unity 5) to return to this one.

The reason for it being private is to minimize memory churn. For things like the gravity vector, that are only created once per game/simulation, it's not a big deal.
For things that happen frequently, like impulses, this can cause a lot of performance degradation.
If you create a lot of new b2Vec2's every frame, and those objects are only needed for that single frame, they will all need to be cleaned up by garbage collection eventually. Each time one of these garbage collections happens, the page locks up until it finishes. The more objects that need to be checked for cleanup, the longer the lockup, the worse the performance hit.

If you've got simple b2Worlds (<100 objects, most static, few collisions), this performance hit is barely noticeable. But if you've got something complicated, these garbage collection spikes can easily get bad enough to last over a second each, and happen multiple times per minute.
Take a look at "tumbler" and "tumbler-comparison" for examples that show this. "tumbler" uses box2dweb-closure, with all the internal b2Vec2 uses converted to b2Vec2.Get/b2Vec2.Free, "tumbler-comparison" uses box2dweb, which creates lots of new b2Vec2 instances for all the internal logic.

Note: It has been a long time since I've run the tumbler comparisons - javascript performance may be fast enough now that you need more than 800 objects to see a significant difference. Look for the "var stepsLeft = 800;" line in each of the test.js files, and increase that number if they're both getting 60fps.

**Comment by Vlad-UA** [comment]
Thank you for the detailed explanation.
I use box2dweb-closure library in my physic games (example http://angry-animals.net/html5/pooltable2/pooltable2.html)
And they have good performance on low level mobile devices too (example of pool table on the iPad 1 https://www.youtube.com/watch?v=0C9JRlrW_X0 and iPod Touch 2 https://www.youtube.com/watch?v=t8qyVafAcLU )
I will create another one mobile physic game soon. It has more physics actions and I try to understand how to get maximum performance on low level devices.
